package com.rk.postmeterreader;

public class DbfConstant {
    public class Colume {
        public static final String CBJHBH = "CBJHBH";       //抄表计划编号        营销      VARCHAR2(20)
        public static final String CBQDBH = "CBQDBH";       //抄表区段编号        营销      VARCHAR2(20)
        public static final String CBYWLXDM = "CBYWLXDM";   //抄表业务类型代码    营销      VARCHAR2(8)
        public static final String CBQDMC = "CBQDMC";       //抄表区段名称        营销      VARCHAR2(64)
        public static final String CBSXH = "CBSXH";         //抄表顺序号          营销      NUMBER(5)
        public static final String JLDBH = "JLDBH";         //计量点编号          营销      VARCHAR2(20)
        public static final String YXDNBBS = "YXDNBBS";     //运行电能表标识      营销      VARCHAR2(16)
        public static final String SSLXDM = "SSLXDM";       //示数类型            营销      VARCHAR2(8)
        public static final String ZFBBZ = "ZFBBZ";         //主副表标志          营销      VARCHAR2(8)
        public static final String DFNY = "DFNY";           //电费年月            营销      NUMBER(6)
        public static final String BQCBCS = "BQCBCS";       //本期抄表次数        营销      NUMBER(5)
        public static final String YHBH = "YHBH";           //用户编号            营销      VARCHAR2(20)
        public static final String YHMC = "YHMC";           //用户名称            营销      VARCHAR2(200
        public static final String YDDZ = "YDDZ";           //用电地址            营销      VARCHAR2(200
        public static final String ZCBH = "ZCBH";           //资产编号            营销      VARCHAR2(32)
        public static final String CCBH = "CCBH";           //出厂编号            营销      VARCHAR2(32)
        public static final String SCBSS = "SCBSS";         //上次表示数          营销      NUMBER(13,5)
        public static final String BCBSS = "BCBSS";         //本次表示数          抄表器    NUMBER(13,5)
        public static final String BMWS = "BMWS";           //表码位数            营销      VARCHAR2(8)
        public static final String ZHBL = "ZHBL";           //综合倍率            营销      NUMBER(10,3)
        public static final String SCCBRQ = "SCCBRQ";       //上次抄表日期        营销      NUMBER(8)
        public static final String SCBJDL = "SCBJDL";       //上次表计电量        营销      NUMBER(14,2)
        public static final String CBBZDM = "CBBZDM";       //抄表标志代码        抄表器    VARCHAR2(8)
        public static final String CBZTDM = "CBZTDM";       //抄表状态代码        抄表器    VARCHAR2(8)
        public static final String CBYCDM = "CBYCDM";       //抄表异常代码        抄表器    VARCHAR2(8)
        public static final String GDDWBM = "GDDWBM";       //供电单位编码        营销      VARCHAR2(20)
        public static final String LXDH = "LXDH";           //联系电话            营销      VARCHAR2(20)
        public static final String CBSJ = "CBSJ";           //抄表时间            抄表器    VARCHAR(20)
        public static final String SFGXBZ = "SFGXBZ";       //是否新表标志        营销      VARCHAR2(8)
        public static final String QFQS = "QFQS";           //欠费期数            营销      NUMBER(8)
        public static final String QFNY = "QFNY";           //欠费年月            营销      NUMBER(8)
        public static final String ZQFJE = "ZQFJE";         //总欠费金额          营销      NUMBER(14,2)
        public static final String CFJG = "CFJG";           //催费结果            抄表器    VARCHAR2(32)
        public static final String DJMC = "DJMC";           //电价名称            营销      VARCHAR2(96)
        public static final String DJ = "DJ";               //电价                营销      NUMBER(9,7)
        public static final String SJCBFS = "SJCBFS";       //实际抄表方式        抄表器    VARCHAR2(8)
        public static final String JZQBH = "JZQBH";         //集中器编号          营销      VARCHAR2(32)
        public static final String JZQTNH = "JZQTNH";       //集中器TN号          营销      NUMBER(4)
        public static final String KHLB = "KHLB";           //客户类别            营销      VARCHAR2(8)
        public static final String JCBZ = "JCBZ";           //监抄标志            营销      CHAR(1)
        public static final String JCJL = "JCJL";           //监抄结论            抄表器    VARCHAR2(12)
        public static final String TXMBH = "TXMBH";         //条形码编号          营销      VARCHAR2(12)
        public static final String YHH = "YHH";             //原户号              营销      VARCHAR2(20)
        public static final String CKBXH = "CKBXH";         //参考表序号          营销      NUMBER(5)
        public static final String JLDLB = "JLDLB";         //计量点类别          营销      CHAR(1)
        public static final String XW = "XW";               //相位                营销      CHAR(1)
        public static final String SCCBYCBZ = "SCCBYCBZ";   //上次抄表异常标志    营销      VARCHAR2(8)
        public static final String XHWDZ = "XHWDZ";         //新红外地址          抄表器    VARCHAR2(32)
        public static final String JHWDZ = "JHWDZ";         //旧红外地址          营销      VARCHAR2(32)
        public static final String QYBZ = "QYBZ";           //区域标志            营销      CHAR(1)
        public static final String ZJDL = "ZJDL";           //增减电量            营销      NUMBER(14,2)
        public static final String HBDL = "HBDL";           //换表电量            营销      NUMBER(14,2)
        public static final String SFCDBZ = "SFCDBZ";       //是否出单标志        抄表器    VARCHAR2(1)
        public static final String DJBMBZ = "DJBMBZ";       //冻结表码标志                  VARCHAR2(1)
        public static final String DJSJ = "DJSJ";           //登记时间                      VARCHAR2(20)
        public static final String BZ = "BZ";               //备注                抄表器    VARCHAR(20)
        public static final String YCBH = "YCBH";           //原抄表号                      VARCHAR2(20)
    }
}
